"""Fuse-overlayfs utilities for isolated script execution.

This module provides functions to create isolated execution environments
using fuse-overlayfs. Each script run gets its own overlay where:
- lowerdir: the base repository (read-only)
- upperdir: changes made during this run (including overlay bundle)
- workdir: internal fuse-overlayfs working directory
- merged: the combined view where the script runs

This allows multiple scripts to run concurrently without interfering
with each other, as each gets its own isolated view of the repository.
"""

from __future__ import annotations

import shlex
from uuid import uuid4


def generate_run_id() -> str:
    """Generate a unique run ID for an overlay mount."""
    return uuid4().hex[:12]


def get_overlay_paths(run_id: str) -> dict[str, str]:
    """Get the paths for an overlay mount.

    Returns a dict with keys: base_dir, upper, work, merged
    All paths use /tmp for local (fast) storage on compute nodes.
    """
    base_dir = f"/tmp/idun-overlay-{run_id}"
    return {
        "base_dir": base_dir,
        "upper": f"{base_dir}/upper",
        "work": f"{base_dir}/work",
        "merged": f"{base_dir}/merged",
    }


def build_mount_commands(
    run_id: str,
    repo_path: str,
    overlay_path: str | None = None,
) -> list[str]:
    """Build shell commands to create and mount a fuse-overlayfs.

    Args:
        run_id: Unique identifier for this run
        repo_path: Path to the base repository (lowerdir)
        overlay_path: Optional path to overlay tarball to extract

    Returns:
        List of shell commands to execute
    """
    paths = get_overlay_paths(run_id)
    commands: list[str] = []

    # Create directories
    commands.append(f"mkdir -p {paths['upper']} {paths['work']} {paths['merged']}")

    # Extract overlay bundle to upperdir if provided
    # Note: Don't use shlex.quote() here because overlay_path contains $HOME
    # which needs shell expansion. The path is generated by us, so it's safe.
    if overlay_path:
        commands.append(
            f'if [ -f "{overlay_path}" ]; then '
            f'tar -xzf "{overlay_path}" -C {paths["upper"]}; '
            f"fi"
        )
        # Handle deleted files manifest
        commands.append(
            f"if [ -f {paths['upper']}/.idun_deleted.txt ]; then "
            f"while IFS= read -r path; do "
            f'[ -n "$path" ] && mkdir -p $(dirname {paths["upper"]}/"$path") && '
            f'mknod {paths["upper"]}/"$path" c 0 0 2>/dev/null || true; '
            f"done < {paths['upper']}/.idun_deleted.txt; "
            f"rm -f {paths['upper']}/.idun_deleted.txt; "
            f"fi"
        )

    # Mount fuse-overlayfs
    # Note: The lowerdir is the base repo, upperdir captures all changes
    mount_cmd = (
        f"fuse-overlayfs "
        f"-o lowerdir={repo_path},"
        f"upperdir={paths['upper']},"
        f"workdir={paths['work']} "
        f"{paths['merged']}"
    )
    commands.append(mount_cmd)

    return commands


def build_unmount_commands(run_id: str) -> list[str]:
    """Build shell commands to unmount and cleanup an overlay.

    Args:
        run_id: Unique identifier for this run

    Returns:
        List of shell commands to execute
    """
    paths = get_overlay_paths(run_id)
    commands: list[str] = []

    # Unmount (use fusermount3 which is available on IDUN)
    commands.append(f"fusermount3 -u {paths['merged']} 2>/dev/null || true")

    return commands


def build_cleanup_commands(run_id: str, keep_artifacts: bool = False) -> list[str]:
    """Build shell commands to cleanup overlay directories.

    Args:
        run_id: Unique identifier for this run
        keep_artifacts: If True, don't remove the upper directory

    Returns:
        List of shell commands to execute
    """
    paths = get_overlay_paths(run_id)
    commands: list[str] = []

    if keep_artifacts:
        # Only remove work and merged, keep upper for artifacts
        commands.append(f"rm -rf {paths['work']} {paths['merged']} 2>/dev/null || true")
    else:
        # Remove entire overlay directory
        commands.append(f"rm -rf {paths['base_dir']} 2>/dev/null || true")

    return commands


def build_artifact_collection_commands(
    run_id: str,
    artifact_dest: str,
    patterns: list[str] | None = None,
) -> list[str]:
    """Build shell commands to collect artifacts from an overlay run.

    Artifacts are files that were created or modified during the run,
    which are automatically captured in the upperdir.

    Args:
        run_id: Unique identifier for this run
        artifact_dest: Destination directory for artifacts
        patterns: Optional list of glob patterns to filter (e.g., ["*.md", "*.pdf"])
                  If None, copies all files from upperdir.

    Returns:
        List of shell commands to execute
    """
    paths = get_overlay_paths(run_id)
    commands: list[str] = []

    # Create destination directory with run_id subdirectory
    dest_dir = f"{artifact_dest}/{run_id}"
    commands.append(f"mkdir -p {dest_dir}")

    if patterns:
        # Copy only matching files
        for pattern in patterns:
            # Use find to locate matching files and copy them preserving structure
            commands.append(
                f"find {paths['upper']} -name {shlex.quote(pattern)} -type f "
                f"-exec sh -c 'for f; do "
                f"rel=${{f#{paths['upper']}/}}; "
                f'mkdir -p {dest_dir}/$(dirname "$rel"); '
                f'cp "$f" {dest_dir}/"$rel"; '
                f"done' _ {{}} +"
            )
    else:
        # Copy all files from upperdir
        commands.append(
            f'if [ -d {paths["upper"]} ] && [ "$(ls -A {paths["upper"]})" ]; then '
            f"cp -r {paths['upper']}/. {dest_dir}/; "
            f"fi"
        )

    return commands


def build_full_overlay_script_commands(
    run_id: str,
    repo_path: str,
    overlay_path: str | None,
    script_commands: list[str],
    collect_artifacts: bool = False,
    artifact_dest: str | None = None,
    artifact_patterns: list[str] | None = None,
) -> list[str]:
    """Build complete shell commands for an overlay-isolated script run.

    This combines mount, script execution, artifact collection, and cleanup
    into a single sequence of commands with proper error handling.

    Args:
        run_id: Unique identifier for this run
        repo_path: Path to the base repository
        overlay_path: Optional path to overlay tarball
        script_commands: Commands to run inside the overlay
        collect_artifacts: Whether to collect artifacts after run
        artifact_dest: Destination for artifacts (required if collect_artifacts=True)
        artifact_patterns: Optional patterns to filter artifacts

    Returns:
        List of shell commands to execute
    """
    paths = get_overlay_paths(run_id)
    commands: list[str] = []

    # Setup: create dirs and mount
    commands.extend(build_mount_commands(run_id, repo_path, overlay_path))

    # Change to merged directory for script execution
    commands.append(f"cd {paths['merged']}")

    # Add trap for cleanup on exit/error
    cleanup_cmd = (
        f"fusermount3 -u {paths['merged']} 2>/dev/null; rm -rf {paths['base_dir']}"
    )
    if collect_artifacts and artifact_dest:
        # Modified cleanup: collect artifacts first, then cleanup
        artifact_cmds = build_artifact_collection_commands(
            run_id, artifact_dest, artifact_patterns
        )
        artifact_cmd_str = "; ".join(artifact_cmds)
        cleanup_cmd = (
            f"fusermount3 -u {paths['merged']} 2>/dev/null; "
            f"{artifact_cmd_str}; "
            f"rm -rf {paths['base_dir']}"
        )
    commands.append(f"trap '{cleanup_cmd}' EXIT")

    # Run the actual script commands
    commands.extend(script_commands)

    return commands
