"""
This type stub file was generated by pyright.
"""

from flask.config import Config

flask_installed = ...

class FlaskDynaconf:
    """The arguments are.
    app = The created app
    dynaconf_args = Extra args to be passed to Dynaconf (validator for example)

    All other values are stored as config vars specially::

        ENVVAR_PREFIX_FOR_DYNACONF = env prefix for your envvars to be loaded
                            example:
                                if you set to `MYSITE` then
                                export MYSITE_SQL_PORT='@int 5445'

                            with that exported to env you access using:
                                app.config.SQL_PORT
                                app.config.get('SQL_PORT')
                                app.config.get('sql_port')
                                # get is case insensitive
                                app.config['SQL_PORT']

                            Dynaconf uses `@int, @bool, @float, @json` to cast
                            env vars

        SETTINGS_FILE_FOR_DYNACONF = The name of the module or file to use as
                                    default to load settings. If nothing is
                                    passed it will be `settings.*` or value
                                    found in `ENVVAR_FOR_DYNACONF`
                                    Dynaconf supports
                                    .py, .yml, .toml, ini, json

    ATTENTION: Take a look at `settings.yml` and `.secrets.yml` to know the
            required settings format.

    Settings load order in Dynaconf:

    - Load all defaults and Flask defaults
    - Load all passed variables when applying FlaskDynaconf
    - Update with data in settings files
    - Update with data in environment vars `ENVVAR_FOR_DYNACONF_`


    TOML files are very useful to have `envd` settings, lets say,
    `production` and `development`.

    You can also achieve the same using multiple `.py` files naming as
    `settings.py`, `production_settings.py` and `development_settings.py`
    (see examples/validator)

    Example::

        app = Flask(__name__)
        FlaskDynaconf(
            app,
            ENV='MYSITE',
            SETTINGS_FILE='settings.yml',
            EXTRA_VALUE='You can add additional config vars here'
        )

    Take a look at examples/flask in Dynaconf repository

    """
    def __init__(
        self,
        app=...,
        instance_relative_config=...,
        dynaconf_instance=...,
        extensions_list=...,
        **kwargs,
    ) -> None:
        """kwargs holds initial dynaconf configuration"""
        ...

    def init_app(self, app, **kwargs):  # -> None:
        """kwargs holds initial dynaconf configuration"""
        ...

    def make_config(self, app):  # -> DynaconfConfig:
        ...

class DynaconfConfig(Config):
    """
    Replacement for flask.config_class that responds as a Dynaconf instance.
    """
    def __init__(self, _settings, _app, *args, **kwargs) -> None:
        """perform the initial load"""
        ...

    def __contains__(self, item):  # -> bool:
        ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value):
        """
        Allows app.config['key'] = 'foo'
        """
        ...

    def keys(self):  # -> KeysView[Any]:
        ...
    def values(self):  # -> ValuesView[Any]:
        ...
    def items(self):  # -> ItemsView[Any, Any]:
        ...
    def setdefault(self, key, value=...):  # -> None:
        ...
    def __iter__(self):  # -> Iterator[Any]:
        ...
    def __getattr__(self, name):  # -> Any:
        """
        First try to get value from dynaconf then from Flask Config
        """
        ...

    def __call__(self, name, *args, **kwargs): ...
    def get(self, key, default=...):
        """Gets config from dynaconf variables
        if variables does not exists in dynaconf try getting from
        `app.config` to support runtime settings."""
        ...

    def load_extensions(self, key=..., app=...):  # -> None:
        """Loads flask extensions dynamically."""
        ...
