"""
This type stub file was generated by pyright.
"""

import os
import warnings
from collections import defaultdict
from json import JSONDecoder
from pathlib import Path
from typing import Any, Iterator, TYPE_CHECKING, TypeVar
from dynaconf.base import LazySettings, Settings
from dynaconf.utils.boxing import DynaBox

if TYPE_CHECKING: ...
BANNER = ...
if os.name == "nt":
    BANNER = ...

def object_merge(
    old: Any, new: Any, unique: bool = ..., full_path: list[str] = ...
) -> Any:
    """
    Recursively merge two data structures, new is mutated in-place.

    :param old: The existing data.
    :param new: The new data to get old values merged in to.
    :param unique: When set to True existing list items are not set.
    :param full_path: Indicates the elements of a tree.
    """
    ...

def recursive_get(
    obj: DynaBox | dict[str, int] | dict[str, str | int], names: list[str] | None
) -> Any:
    """Given a dot accessible object and a list of names `foo.bar.zaz`
    gets recursively all names one by one obj.foo.bar.zaz.
    """
    ...

def handle_metavalues(
    old: DynaBox | dict[str, int] | dict[str, str | int], new: Any
) -> None:
    """Cleanup of MetaValues on new dict"""
    ...

class DynaconfDict(dict):
    """A dict representing en empty Dynaconf object
    useful to run loaders in to a dict for testing"""
    def __init__(self, *args, **kwargs) -> None: ...
    def set(self, key: str, value: str, *args, **kwargs) -> None: ...
    @staticmethod
    def get_environ(key, default=...):  # -> str | None:
        ...
    def exists(self, key: str, **kwargs) -> bool: ...

RENAMED_VARS = ...

def compat_kwargs(kwargs: dict[str, Any]) -> None:
    """To keep backwards compat change the kwargs to new names"""
    ...

class Missing:
    """
    Sentinel value object/singleton used to differentiate between ambiguous
    situations where `None` is a valid value.
    """
    def __bool__(self) -> bool:
        """Respond to boolean duck-typing."""
        ...

    def __eq__(self, other: DynaBox | Missing) -> bool:
        """Equality check for a singleton."""
        ...

    __nonzero__ = ...
    def __repr__(self) -> str:
        """
        Unambiguously identify this string-based representation of Missing,
        used as a singleton.
        """
        ...

missing = ...

def deduplicate(list_object: list[str]) -> list[str]:
    """Rebuild `list_object` removing duplicated and keeping order"""
    ...

def warn_deprecations(data: Any) -> None: ...
def trimmed_split(s: str, seps: str | tuple[str, str] = ...) -> list[str]:
    """Given a string s, split is by one of one of the seps."""
    ...

T = TypeVar("T")

def ensure_a_list(data: T | list[T]) -> list[T]:
    """Ensure data is a list or wrap it in a list"""
    ...

def build_env_list(obj: Settings | LazySettings, env: str | None) -> list[str]:
    """Build env list for loaders to iterate.

    Arguments:
        obj {LazySettings} -- A Dynaconf settings instance
        env {str} -- The current env to be loaded

    Returns:
        [str] -- A list of string names of the envs to load.
    """
    ...

def upperfy(key: str) -> str:
    """Receive a string key and returns its upper version.

    Example:

      input: foo
      output: FOO

      input: foo_bar
      output: FOO_BAR

      input: foo__bar__ZAZ
      output: FOO__bar__ZAZ

    Arguments:
        key {str} -- A string key that may contain dunders `__`

    Returns:
        The key as upper case but keeping the nested elements.
    """
    ...

def multi_replace(text: str, patterns: dict[str, str]) -> str:
    """Replaces multiple pairs in a string

    Arguments:
        text {str} -- A "string text"
        patterns {dict} -- A dict of {"old text": "new text"}

    Returns:
        text -- str
    """
    ...

def extract_json_objects(
    text: str, decoder: JSONDecoder = ...
) -> Iterator[dict[str, int | dict[Any, Any]]]:
    """Find JSON objects in text, and yield the decoded JSON data

    Does not attempt to look for JSON arrays, text, or other JSON types outside
    of a parent JSON object.

    """
    ...

def recursively_evaluate_lazy_format(
    value: Any, settings: Settings | LazySettings
) -> Any:
    """Given a value as a data structure, traverse all its members
    to find Lazy values and evaluate it.

    For example: Evaluate values inside lists and dicts
    """
    ...

def isnamedtupleinstance(value):  # -> bool:
    """Check if value is a namedtuple instance

    stackoverflow.com/questions/2166818/
    how-to-check-if-an-object-is-an-instance-of-a-namedtuple
    """
    ...

def find_the_correct_casing(key: str, data: dict[str, Any]) -> str | None:
    """Given a key, find the proper casing in data.

    Return 'None' for non-str key types.

    Arguments:
        key {str} -- A key to be searched in data
        data {dict} -- A dict to be searched

    Returns:
        str -- The proper casing of the key in data
    """
    ...

def prepare_json(data: Any) -> Any:
    """Takes a data dict and transforms unserializable values to str for JSON.
    {1: PosixPath("/foo")} -> {"1": "/foo"}
    """
    ...
