"""
This type stub file was generated by pyright.
"""

from dynaconf.vendor.box import Box

def evaluate_lazy_format(f):  # -> _Wrapped[..., Any, ..., Any]:
    """Marks a method on Dynabox instance to
    lazily evaluate LazyFormat objects upon access."""
    ...

class DynaBox(Box):
    """Specialized Box for dynaconf
    it allows items/attrs to be found both in upper or lower case"""
    @evaluate_lazy_format
    def __getattr__(self, item, *args, **kwargs):  # -> Self | BoxList | bool | Any:
        ...
    @evaluate_lazy_format
    def __getitem__(self, item, *args, **kwargs):  # -> Self | BoxList | bool:
        ...
    def __copy__(self):  # -> Self:
        ...
    def copy(self):  # -> Self:
        ...
    @evaluate_lazy_format
    def get(
        self, item, default=..., *args, **kwargs
    ):  # -> Self | BoxList | bool | Box | object | None:
        ...
    def __dir__(self):  # -> list[Any]:
        ...
