"""
This type stub file was generated by pyright.
"""

SEARCHTREE = ...

def find_file(filename=..., project_root=..., skip_files=..., **kwargs):
    """Search in increasingly higher folders for the given file
    Returns path to the file if found, or an empty string otherwise.

    This function will build a `search_tree` based on:

    - Project_root if specified
    - Invoked script location and its parents until root
    - Current working directory

    For each path in the `search_tree` it will also look for an
    additional `./config` folder.
    """
    ...

def read_file(path, **kwargs): ...
def get_local_filename(filename):  # -> str:
    """Takes a filename like `settings.toml` and returns `settings.local.toml`

    Arguments:
        filename {str} -- The filename or complete path

    Returns:
        [str] -- The same name or path with `.local.` added.
    """
    ...

magic_check = ...
magic_check_bytes = ...

def has_magic(s):  # -> bool:
    """Taken from python glob module"""
    ...

def glob(
    pathname, *, root_dir=..., dir_fd=..., recursive=..., include_hidden=...
):  # -> list[Any]:
    """Redefined std glob assuming some defaults.
    and fallback for diffente python versions."""
    ...
