"""
This type stub file was generated by pyright.
"""

from pathlib import PosixPath
from typing import Any, Callable, Literal, Protocol, TYPE_CHECKING, TextIO, Union
from dynaconf.loaders.base import SourceMetadata
from dynaconf.base import LazySettings, Settings

"""Inspecting module"""
if TYPE_CHECKING: ...
json_pretty = ...
json_compact = ...

def yaml_dumper_with_defaults(data: dict, text_stream: TextIO) -> None:
    """Easier way to get YAML dumper to handle unseralizable types"""
    ...

builtin_dumpers = ...
DumperPreset = Union[Literal["yaml"], Literal["json"], Literal["json-compact"]]

class DumperType(Protocol):
    def __call__(self, data: dict, text_stream: TextIO) -> None: ...

class ReportBuilderType(Protocol):
    def __call__(
        self,
        *,
        key: str | None,
        env: str | None,
        new_first: bool | None,
        include_internal: bool | None,
        history_limit: int | None,
        current: Any,
        history: list[dict] | None,
    ) -> dict: ...

class KeyNotFoundError(Exception): ...
class EnvNotFoundError(Exception): ...
class OutputFormatError(Exception): ...

def inspect_settings(
    settings: Settings | LazySettings,
    key: str | None = ...,
    env: str | None = ...,
    *,
    new_first: bool = ...,
    history_limit: int | None = ...,
    include_internal: bool = ...,
    to_file: str | PosixPath | None = ...,
    print_report: bool = ...,
    dumper: DumperPreset | DumperType | None = ...,
    report_builder: ReportBuilderType | None = ...,
):  # -> dict[Any, Any]:
    """
    Print and return the loading history of a settings object.

    Optional arguments must be provided as kwargs.

    :param settings: A Dynaconf instance
    :param key: String dotted path. E.g "path.to.key"
    :param env: Filter by this env

    :param new_first: If True, uses newest to oldest loading order
    :param history_limit: Limits how many entries are shown
    :param include_internal: If True, include internal loaders (e.g. defaults).
        This has effect only if key is not provided.
    :param to_file: If specified, write to this filename
    :param print_report: If true, prints the dumped report to stdout
    :param dumper: Accepts preset strings (e.g. "yaml", "json") or custom
        dumper callable ``(dict, TextIO) -> None``. Defaults to "yaml"
    :param report_builder: if provided, it is used to generate the report

    :return: Dict with a dict containing report data
    :rtype: dict
    """
    ...

def get_history(
    obj: Settings | LazySettings,
    key: str | None = ...,
    *,
    filter_callable: Callable[[SourceMetadata], bool] | None = ...,
    include_internal: bool = ...,
    history_limit: int | None = ...,
) -> list[dict]:
    """
    Gets data from `settings.loaded_by_loaders` in order of loading with
    optional filtering options.

    Returns a list of dict in new-first order, where the dict contains the
    data and it's source metadata.

    :param obj: Setting object which contain the data
    :param key: Key path to desired key. Use all if not provided
    :param filter_callable: Takes SourceMetadata and returns a boolean
    :param include_internal: If True, include internal loaders (e.g. defaults).
        This has effect only if key is not provided.
    history_limit: limits how many entries are shown

    Example:
        >>> settings = Dynaconf(...)
        >>> _get_history(settings)
        [
            {
                "loader": "yaml"
                "identifier": "path/to/file.yml"
                "env": "default"
                "data": {"foo": 123, "spam": "eggs"}
            },
            ...
        ]
    """
    ...

def get_debug_info(
    settings: Settings | LazySettings, verbosity: int = ..., key: str | None = ...
) -> dict:
    """Returns a dict with debug info about the settings object"""
    ...

def print_debug_info(
    settings: Settings | LazySettings,
    *,
    dumper: DumperPreset | DumperType | None = ...,
    verbosity: int = ...,
    key: str | None = ...,
):  # -> None:
    """Calls dumper with settings debug info"""
    ...
