"""
This type stub file was generated by pyright.
"""

jinja_env = ...
true_values = ...
false_values = ...
KV_PATTERN = ...

class DynaconfFormatError(Exception):
    """Error to raise when formatting a lazy variable fails"""

    ...

class DynaconfParseError(Exception):
    """Error to raise when parsing @casts"""

    ...

class MetaValue:
    """A Marker to trigger specific actions on `set` and `object_merge`"""

    _meta_value = ...
    def __init__(self, value, box_settings) -> None: ...
    def __repr__(self):  # -> str:
        ...
    def unwrap(
        self,
    ):  # -> Any | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None:
        ...

class Reset(MetaValue):
    """Triggers an existing key to be reset to its value
    NOTE: DEPRECATED on v3.0.0
    """

    _dynaconf_reset = ...
    def __init__(self, value, box_settings) -> None: ...

class Del(MetaValue):
    """Triggers an existing key to be deleted"""

    _dynaconf_del = ...
    def unwrap(self): ...

class Merge(MetaValue):
    """Triggers an existing key to be merged"""

    _dynaconf_merge = ...
    def __init__(self, value, box_settings, unique=...) -> None: ...

class Insert(MetaValue):
    """Triggers the value to be inserted into a list at specific index"""

    _dynaconf_insert = ...
    def __init__(self, value, box_settings) -> None:
        """
        normally value will be a string like
        `0 foo` or `-1 foo` and needs to get split
        but value can also be just a single string with or without space
        like `foo` and in this case it will be treated as `0 foo`
        but it can also be `foo bar` and in this case it will be treated as `0 foo bar`
        we need to check if the first part is a number
        if it is not a number then we will treat it as `0 value`
        if it is a number then we will split it as `index, value`
        this must use a regex to match value, examples:
            -1 foo -> index = -1, value = foo
            0 foo -> index = 0, value = foo
            0 foo bar -> index = 0, value = foo bar
            0 42 -> index = 0, value = 42
            0 42 foo -> index = 0, value = 42 foo
            foo -> index = 0, value = foo
            foo bar -> index = 0, value = foo bar
            42 -> index = 0, value = 42
            42 foo -> index = 42, value = foo
            42 foo bar -> index = 42, value = foo bar
        """
        ...

class BaseFormatter:
    def __init__(self, function, token) -> None: ...
    def __call__(self, value, **context): ...
    def __str__(self) -> str: ...

class Formatters:
    """Dynaconf builtin formatters"""

    python_formatter = ...
    jinja_formatter = ...
    get_formatter = ...

class Lazy:
    """Holds data to format lazily."""

    _dynaconf_lazy_format = ...
    def __init__(self, value=..., formatter=..., casting=...) -> None: ...
    @property
    def context(self):  # -> dict[str, _Environ[str] | Any]:
        """Builds a context for formatting."""
        ...

    def __call__(self, settings, validator_object=...):
        """LazyValue triggers format lazily."""
        ...

    def __str__(self) -> str:
        """Gives string representation for the object."""
        ...

    def __repr__(self):  # -> str:
        """Give the quoted str representation"""
        ...

    def set_casting(self, casting):  # -> Self:
        """Set the casting and return the instance."""
        ...

def try_to_encode(value, callback=...):  # -> str:
    """Tries to encode a value by verifying existence of `_dynaconf_encode`"""
    ...

def evaluate_lazy_format(f):  # -> _Wrapped[..., Any, ..., Any]:
    """Marks a method on Settings instance to
    lazily evaluate LazyFormat objects upon access."""
    ...

converters = ...

def apply_converter(
    converter_key, value, box_settings
):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | None:
    """
    Get converter and apply it to @value.

    Lazy converters will return Lazy objects for later evaluation.
    """
    ...

def add_converter(converter_key, func):  # -> None:
    """Adds a new converter to the converters dict"""
    ...

def parse_with_toml(data):
    """Uses TOML syntax to parse data"""
    ...

def parse_conf_data(
    data, tomlfy=..., box_settings=...
):  # -> list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Any | Empty | None:
    """
    Apply parsing tokens recursively and return transformed data.

    Strings with lazy parser (e.g, @format) will become Lazy objects.
    """
    ...

def unparse_conf_data(value):  # -> str:
    ...
def boolean_fix(value: str | None):  # -> str | None:
    """Gets a value like `True/False` and turns to `true/false`
    This function exists because of issue #976
    Toml parser casts booleans from true/false lower case
    however envvars are usually exported as True/False capitalized
    by mistake, this helper fixes it for envvars only.

    Assume envvars are always str.
    """
    ...
