"""
This type stub file was generated by pyright.
"""

import importlib
import os
from contextlib import suppress
from typing import Callable, TYPE_CHECKING
from dynaconf import constants as ct, default_settings
from dynaconf.loaders import (
    ini_loader,
    json_loader,
    py_loader,
    toml_loader,
    yaml_loader,
)
from dynaconf.loaders.base import SourceMetadata
from dynaconf.utils import deduplicate, ensure_a_list
from dynaconf.utils.boxing import DynaBox
from dynaconf.utils.files import get_local_filename, glob, has_magic
from dynaconf.utils.parse_conf import false_values
from dynaconf.base import Settings

if TYPE_CHECKING: ...

def default_loader(obj, defaults=...):  # -> None:
    """Initial loader for the initialization process.

    Steps:
    - Load default settings (from static module) + kwargs overrides (together)
    - Load envvar overrides
    """
    ...

def execute_instance_hooks(
    obj: Settings, hook_type: str, hook_functions: list[Callable]
):  # -> None:
    """Execute hooks provided by Setting instance"""
    ...

def execute_module_hooks(
    hook, obj, env=..., silent=..., key=..., modules=..., files=...
):  # -> None:
    """Execute dynaconf_hooks from module or filepath."""
    ...

execute_hooks = ...

def settings_loader(
    obj,
    settings_module=...,
    env=...,
    silent=...,
    key=...,
    filename=...,
    validate=...,
    identifier=...,
):  # -> None:
    """Loads from defined settings module

    :param obj: A dynaconf instance
    :param settings_module: A path or a list of paths e.g settings.toml
    :param env: Env to look for data defaults: development
    :param silent: Boolean to raise loading errors
    :param key: Load a single key if provided
    :param filename: optional filename to override the settings_module
    :param validate: If True validate the loaded data
    :param identifier: A string or SourceMetadata to identify the loader
    """
    ...

def load_from_env_named_file(obj, env, key, validate, identifier, mod_file):  # -> None:
    """Load from env named file e.g: development_settings.py"""
    ...

def enable_external_loaders(obj):  # -> None:
    """Enable external service loaders like `VAULT_` and `REDIS_`
    looks forenv variables like `REDIS_ENABLED_FOR_DYNACONF`
    """
    ...

def write(filename, data, env=..., merge=...):  # -> None:
    """Writes `data` to `filename` infers format by file extension."""
    ...
