"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple

class BaseLoader:
    """Base loader for dynaconf source files.

    :param obj: {[LazySettings]} -- [Dynaconf settings]
    :param env: {[string]} -- [the current env to be loaded defaults to
      [development]]
    :param identifier: {[string]} -- [identifier ini, yaml, json, py, toml]
    :param extensions: {[list]} -- [List of extensions with dots ['.a', '.b']]
    :param file_reader: {[callable]} -- [reads file return dict]
    :param string_reader: {[callable]} -- [reads string return dict]
    """
    def __init__(
        self,
        obj,
        env,
        identifier,
        extensions,
        file_reader,
        string_reader,
        opener_params=...,
        validate=...,
    ) -> None:
        """Instantiates a loader for different sources"""
        ...

    @staticmethod
    def warn_not_installed(obj, identifier):  # -> None:
        ...
    def load(self, filename=..., key=..., silent=..., merge=...):  # -> None:
        """
        Reads and loads in to `self.obj` a single key or all keys from source

        :param filename: Optional filename to load
        :param key: if provided load a single key
        :param silent: if load errors should be silenced
        """
        ...

    def get_source_data(self, files):  # -> dict[Any, Any]:
        """Reads each file and returns source data for each file
        {"path/to/file.ext": {"key": "value"}}
        """
        ...

class SourceMetadata(NamedTuple):
    """
    Useful metadata about some loaded source (file, envvar, etc).

    Serve as a unique identifier for data from a specific env
    and a specific source (file, envvar, validationd default, etc)

    Examples:
        SourceMetadata(loader="envvar", identifier="os", env="global")
        SourceMetadata(loader="yaml", identifier="path/to/file.yml", env="dev")
    """

    loader: str
    identifier: str
    env: str = ...
    merged: bool = ...
