"""
This type stub file was generated by pyright.
"""

DOTENV_IMPORTED = ...
IDENTIFIER_PREFIX = ...

def load(obj, env=..., silent=..., key=..., validate=..., identifier=...):  # -> None:
    """Loads envvars with prefixes:

    `DYNACONF_` (default global) or `$(ENVVAR_PREFIX_FOR_DYNACONF)_`

    if envvar_prefix is set to:
      str: -> load {str}_*
      str,str1 -> load [{str}_, {str1}_]
      False -> load *
      None -> return not loading anything

    """
    ...

def load_from_env(
    obj, prefix=..., key=..., silent=..., identifier=..., env=..., validate=...
):  # -> None:
    ...
def write(settings_path, settings_data, **kwargs):  # -> None:
    """Write data to .env file"""
    ...
