"""
This type stub file was generated by pyright.
"""

def load(
    obj, settings_module, identifier=..., silent=..., key=..., validate=...
):  # -> None:
    """
    Tries to import a python module

    Notes:
        It doesn't handle environment namespaces explicitly. Eg
            [default], [development], etc
        See tests/test_nested_loading.py sample python file
    """
    ...

def load_from_python_object(
    obj, mod, settings_module, key=..., identifier=..., validate=...
):  # -> None:
    ...
def try_to_load_from_py_module_name(
    obj, name, key=..., identifier=..., silent=..., validate=...
):  # -> bool:
    """Try to load module by its string name.

    Arguments:
        obj {LAzySettings} -- Dynaconf settings instance
        name {str} -- Name of the module e.g: foo.bar.zaz

    Keyword Arguments:
        key {str} -- Single key to be loaded (default: {None})
        identifier {str} -- Name of identifier to store (default: 'py')
        silent {bool} -- Weather to raise or silence exceptions.
    """
    ...

def get_module(
    obj, filename, silent=...
):  # -> tuple[ModuleType | None, Literal['module', 'filename'] | None]:
    ...
def import_from_filename(obj, filename, silent=...):  # -> ModuleType | None:
    """If settings_module is a filename path import it."""
    ...

def write(settings_path, settings_data, merge=...):  # -> None:
    """Write data to a settings file.

    :param settings_path: the filepath
    :param settings_data: a dictionary with data
    :param merge: boolean if existing file should be merged with new data
    """
    ...
