"""
This type stub file was generated by pyright.
"""

def load(
    obj, env=..., silent=..., key=..., filename=..., validate=..., identifier=...
):  # -> None:
    """
    Reads and loads in to "obj" a single key or all keys from source file.

    :param obj: the settings instance
    :param env: settings current env default='development'
    :param silent: if errors should raise
    :param key: if defined load a single key, else load all in env
    :param filename: Optional custom filename to load
    :return: None
    """
    ...

def write(settings_path, settings_data, merge=...):  # -> None:
    """Write data to a settings file.

    :param settings_path: the filepath
    :param settings_data: a dictionary with data
    :param merge: boolean if existing file should be merged with new data
    """
    ...

def encode_nulls(
    data,
):  # -> dict[Any, dict[Any, Any] | list[dict[Any, Any] | list[Any] | Any | str] | Any | str] | list[dict[Any, dict[Any, Any] | list[Any] | Any | str] | list[Any] | Any | str] | Literal['@none ']:
    """TOML does not support `None` so this function transforms to '@none '."""
    ...
