"""
This type stub file was generated by pyright.
"""

from dynaconf.loaders.base import BaseLoader

class AllLoader(BaseLoader):
    """YAML Loader to load multi doc files"""
    def get_source_data(self, files):  # -> dict[Any, Any]:
        ...

def load(
    obj, env=..., silent=..., key=..., filename=..., validate=..., identifier=...
):  # -> None:
    """
    Reads and loads in to "obj" a single key or all keys from source file.

    :param obj: the settings instance
    :param env: settings current env default='development'
    :param silent: if errors should raise
    :param key: if defined load a single key, else load all in env
    :param filename: Optional custom filename to load
    :return: None
    """
    ...

def write(settings_path, settings_data, merge=...):  # -> None:
    """Write data to a settings file.

    :param settings_path: the filepath
    :param settings_data: a dictionary with data
    :param merge: boolean if existing file should be merged with new data
    :param stdout: boolean if should output to stdout instead of file
    """
    ...
