"""
This type stub file was generated by pyright.
"""

from dynaconf.base import LazySettings
from dynaconf.constants import DEFAULT_SETTINGS_FILES
from dynaconf.contrib import DjangoDynaconf, FlaskDynaconf
from dynaconf.hooking import post_hook
from dynaconf.utils.inspect import get_history, inspect_settings
from dynaconf.utils.parse_conf import (
    DynaconfFormatError,
    DynaconfParseError,
    add_converter,
)
from dynaconf.validator import ValidationError, Validator

settings = ...
Dynaconf = LazySettings
__all__ = [
    "Dynaconf",
    "LazySettings",
    "Validator",
    "FlaskDynaconf",
    "ValidationError",
    "DjangoDynaconf",
    "add_converter",
    "inspect_settings",
    "get_history",
    "DynaconfFormatError",
    "DynaconfParseError",
    "post_hook",
]
