"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager
from dynaconf.loaders.base import SourceMetadata
from dynaconf.utils.functional import LazyObject

class LazySettings(LazyObject):
    """Loads settings lazily from multiple sources:

        settings = Dynaconf(
            settings_files=["settings.toml"],  # path/glob
            environments=True,                 # activate layered environments
            envvar_prefix="MYAPP",             # `export MYAPP_FOO=bar`
            env_switcher="MYAPP_MODE",         # `export MYAPP_MODE=production`
            load_dotenv=True,                  # read a .env file
        )

    More options available on https://www.dynaconf.com/configuration/
    """
    def __init__(self, wrapped=..., **kwargs) -> None:
        """
        handle initialization for the customization cases

        :param wrapped: a deepcopy of this object will be wrapped (issue #596)
        :param kwargs: values that overrides default_settings
        """
        ...

    def __getattr__(
        self, name
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """Allow getting keys from self.store using dot notation"""
        ...

    def __call__(self, *args, **kwargs):  # -> Any:
        """Allow direct call of settings('val')
        in place of settings.get('val')
        """
        ...

    def configure(self, settings_module=..., **kwargs):  # -> None:
        """
        Allows user to reconfigure settings object passing a new settings
        module or separated kwargs

        :param settings_module: defines the settings file
        :param kwargs:  override default settings
        """
        ...

    @property
    def configured(self):  # -> bool:
        """If wrapped is configured"""
        ...

class Settings:
    """
    Common logic for settings whether set by a module or by the user.
    """

    dynaconf_banner = ...
    _store = ...
    def __init__(self, settings_module=..., **kwargs) -> None:
        """Execute loaders and custom initialization

        :param settings_module: defines the settings file
        :param kwargs:  override default settings
        """
        ...

    def __call__(
        self, *args, **kwargs
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """Allow direct call of `settings('val')`
        in place of `settings.get('val')`
        """
        ...

    def __setattr__(self, name, value):  # -> None:
        """Allow `settings.FOO = 'value'` while keeping internal attrs."""
        ...

    def __delattr__(self, name):  # -> None:
        """stores reference in `_deleted` for proper error management"""
        ...

    def __contains__(self, item):  # -> bool:
        """Respond to `item in settings`"""
        ...

    def __getattribute__(self, name):  # -> Any:
        ...
    def __getitem__(
        self, item
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """Allow getting variables as dict keys `settings['KEY']`"""
        ...

    def __setitem__(self, key, value):  # -> None:
        """Allow `settings['KEY'] = 'value'`"""
        ...

    @property
    def store(self):  # -> DynaBox:
        """Gets internal storage"""
        ...

    def __dir__(self):  # -> list[str]:
        """Enable auto-complete for code editors"""
        ...

    def __iter__(self):  # -> Generator[Any, Any, None]:
        """Redirects to store object"""
        ...

    def items(self):  # -> list[tuple[Any, Any | DynaBox | BoxList | bool]]:
        """Redirects to store object"""
        ...

    def keys(self):  # -> dict_keys[Any, Any]:
        """Redirects to store object"""
        ...

    def values(self):  # -> list[Any | DynaBox | BoxList | bool]:
        """Redirects to store object"""
        ...

    def setdefault(
        self, item, default, apply_default_on_none=..., env: str = ...
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """Returns value if exists or set it as the given default

        apply_default_on_none: if True, default is set when value is None
        env: used to create the source identifier
        """
        ...

    def as_dict(
        self, env=..., internal=...
    ):  # -> dict[Any, Any | DynaBox | BoxList | bool]:
        """Returns a dictionary with set key and values.

        :param env: Str env name, default self.current_env `DEVELOPMENT`
        :param internal: bool - should include dynaconf internal vars?
        """
        ...

    to_dict = ...
    def get(
        self,
        key,
        default=...,
        cast=...,
        fresh=...,
        dotted_lookup=...,
        parent=...,
        sysenv_fallback=...,
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """
        Get a value from settings store, this is the preferred way to access::

            >>> from dynaconf import settings
            >>> settings.get('KEY')

        :param key: The name of the setting value, will always be upper case
        :param default: In case of not found it will be returned
        :param cast: Should cast in to @int, @float, @bool or @json ?
        :param fresh: Should reload from loaders store before access?
        :param dotted_lookup: Should perform dotted-path lookup?
        :param parent: Is there a pre-loaded parent in a nested data?
        :param sysenv_fallback: Should fallback to system environ if not found?
        :return: The value if found, default or None
        """
        ...

    def exists(self, key, fresh=...):  # -> bool:
        """Check if key exists

        :param key: the name of setting variable
        :param fresh: if key should be taken from source directly
        :return: Boolean
        """
        ...

    def get_fresh(
        self, key, default=..., cast=...
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """This is a shortcut to `get(key, fresh=True)`. always reload from
        loaders store before getting the var.

        :param key: The name of the setting value, will always be upper case
        :param default: In case of not found it will be returned
        :param cast: Should cast in to @int, @float, @bool or @json ?
        :return: The value if found, default or None
        """
        ...

    def get_environ(
        self, key, default=..., cast=...
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[str | list[Any] | <subclass of str and DynaBox> | <subclass of str and dict> | DynaBox | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | <subclass of str and DynaBox> | <subclass of str and dict> | DynaBox | None:
        """Get value from environment variable using os.environ.get

        :param key: The name of the setting value, will always be upper case
        :param default: In case of not found it will be returned
        :param cast: Should cast in to @int, @float, @bool or @json ?
         or cast must be true to use cast inference
        :return: The value if found, default or None
        """
        ...

    def exists_in_environ(self, key):  # -> bool:
        """Return True if env variable is exported"""
        ...

    def as_bool(
        self, key
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """Partial method for get with bool cast"""
        ...

    def as_int(
        self, key
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """Partial method for get with int cast"""
        ...

    def as_float(
        self, key
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """Partial method for get with float cast"""
        ...

    def as_json(
        self, key
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """Partial method for get with json cast"""
        ...

    @property
    def loaded_envs(self):  # -> list[Any]:
        """Get or create internal loaded envs list"""
        ...

    @loaded_envs.setter
    def loaded_envs(self, value):  # -> None:
        """Setter for env list"""
        ...

    loaded_namespaces = ...
    @property
    def loaded_by_loaders(self):  # -> dict[SourceMetadata | str, Any]:
        """Gets the internal mapping of LOADER -> values"""
        ...

    def from_env(self, env=..., keep=..., **kwargs):  # -> LazySettings:
        """Return a new isolated settings object pointing to specified env.

        Example of settings.toml::

            [development]
            message = 'This is in dev'
            [other]
            message = 'this is in other env'

        Program::

            >>> from dynaconf import settings
            >>> print(settings.MESSAGE)
            'This is in dev'
            >>> print(settings.from_env('other').MESSAGE)
            'This is in other env'
            # The existing settings object remains the same.
            >>> print(settings.MESSAGE)
            'This is in dev'

        Arguments:
            env {str} -- Env to load (development, production, custom)

        Keyword Arguments:
            keep {bool} -- Keep pre-existing values (default: {False})
            kwargs {dict} -- Passed directly to new instance.
        """
        ...

    @contextmanager
    def using_env(
        self, env, clean=..., silent=..., filename=...
    ):  # -> Generator[None, Any, None]:
        """
        This context manager allows the contextual use of a different env
        Example of settings.toml::

            [development]
            message = 'This is in dev'
            [other]
            message = 'this is in other env'

        Program::

            >>> from dynaconf import settings
            >>> print settings.MESSAGE
            'This is in dev'
            >>> with settings.using_env('OTHER'):
            ...    print settings.MESSAGE
            'this is in other env'

        :param env: Upper case name of env without any _
        :param clean: If preloaded vars should be cleaned
        :param silent: Silence errors
        :param filename: Custom filename to load (optional)
        :return: context
        """
        ...

    using_namespace = ...
    @contextmanager
    def fresh(self):  # -> Generator[None, Any, None]:
        """
        this context manager force the load of a key direct from the store::

            $ export DYNACONF_VALUE='Original'
            >>> from dynaconf import settings
            >>> print settings.VALUE
            'Original'
            $ export DYNACONF_VALUE='Changed Value'
            >>> print settings.VALUE  # will not be reloaded from env vars
            'Original
            >>> with settings.fresh(): # inside this context all is reloaded
            ...    print settings.VALUE
            'Changed Value'

        an alternative is using `settings.get_fresh(key)`

        :return: context
        """
        ...

    @property
    def current_env(self):  # -> str | Any:
        """Return the current active env"""
        ...

    current_namespace = ...
    @property
    def settings_module(
        self,
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        """Gets SETTINGS_MODULE variable"""
        ...

    settings_file = ...
    def setenv(self, env=..., clean=..., silent=..., filename=...):  # -> None:
        """Used to interactively change the env
        Example of settings.toml::

            [development]
            message = 'This is in dev'
            [other]
            message = 'this is in other env'

        Program::

            >>> from dynaconf import settings
            >>> print settings.MESSAGE
            'This is in dev'
            >>> with settings.using_env('OTHER'):
            ...    print settings.MESSAGE
            'this is in other env'

        :param env: Upper case name of env without any _
        :param clean: If preloaded vars should be cleaned
        :param silent: Silence errors
        :param filename: Custom filename to load (optional)
        :return: context
        """
        ...

    namespace = ...
    def clean(self, *args, **kwargs):  # -> None:
        """Clean all loaded values to reload when switching envs"""
        ...

    def unset(self, key, force=...):  # -> None:
        """Unset on all references

        :param key: The key to be unset
        :param force: Bypass default checks and force unset
        """
        ...

    def unset_all(self, keys, force=...):  # -> None:
        """Unset based on a list of keys

        :param keys: a list of keys
        :param force: Bypass default checks and force unset
        """
        ...

    def set(
        self,
        key,
        value,
        loader_identifier: SourceMetadata | str | None = ...,
        tomlfy=...,
        dotted_lookup=...,
        is_secret=...,
        validate=...,
        merge=...,
    ):  # -> None:
        """Set a value storing references for the loader

        :param key: The key to store. Can be of any type.
        :param value: The raw value to parse and store
        :param loader_identifier: Optional loader name e.g: toml, yaml etc.
                                  Or instance of SourceMetadata
        :param tomlfy: Bool define if value is parsed by toml (defaults False)
        :param merge: Bool define if existing nested data will be merged.
        :param validate: Bool define if validation will be triggered
        """
        ...

    def update(
        self,
        data=...,
        loader_identifier=...,
        tomlfy=...,
        merge=...,
        is_secret=...,
        dotted_lookup=...,
        validate=...,
        **kwargs,
    ):  # -> None:
        """
        Update values in the current settings object without saving in stores::

            >>> from dynaconf import settings
            >>> print settings.NAME
            'Bruno'
            >>> settings.update({'NAME': 'John'}, other_value=1)
            >>> print settings.NAME
            'John'
            >>> print settings.OTHER_VALUE
            1

        :param data: Data to be updated
        :param loader_identifier: Only to be used by custom loaders
        :param tomlfy: Bool define if value is parsed by toml (defaults False)
        :param merge: Bool define if existing nested data will be merged.
        :param validate: Bool define if validators will trigger automatically
        :param kwargs: extra values to update
        :return: None
        """
        ...

    @property
    def loaders(self):  # -> list[Any] | list[ModuleType]:
        """Return available loaders"""
        ...

    def reload(self, env=..., silent=...):  # -> None:
        """Clean end Execute all loaders"""
        ...

    def execute_loaders(
        self, env=..., silent=..., key=..., filename=..., loaders=...
    ):  # -> None:
        """Execute all internal and registered loaders

        :param env: The environment to load
        :param silent: If loading errors is silenced
        :param key: if provided load a single key
        :param filename: optional custom filename to load
        :param loaders: optional list of loader modules
        """
        ...

    def pre_load(self, env, silent, key):  # -> None:
        """Do we have any file to pre-load before main settings file?"""
        ...

    def load_includes(self, env, silent, key):  # -> None:
        """Do we have any nested includes we need to process?"""
        ...

    def load_file(
        self, path=..., env=..., silent=..., key=..., validate=..., run_hooks=...
    ):  # -> None:
        """Programmatically load files from ``path``.

        When using relative paths, the basedir fallbacks in this order:
        - ROOT_PATH_FOR_DYNACONF
        - Directory of the last loaded file
        - CWD

        :param path: A single filename, a glob or a file list
        :param env: Which env to load from file (default current_env)
        :param silent: Should raise errors?
        :param key: Load a single key?
        :param validate: Should trigger validation?
        :param run_hooks: Should run collected hooks?
        """
        ...

    def load_extra_yaml(self, env, silent, key):  # -> None:
        """This is deprecated, kept for compat

        .. deprecated:: 1.0.0
            Use multiple settings or INCLUDES_FOR_DYNACONF files instead.
        """
        ...

    def path_for(self, *args):  # -> str:
        """Path containing _root_path"""
        ...

    def find_file(self, *args, **kwargs): ...
    def flag(self, key, env=...):  # -> bool:
        """Feature flagging system
        write flags to redis
        $ dynaconf write redis -s DASHBOARD=1 -e premiumuser
        meaning: Any premium user has DASHBOARD feature enabled

        In your program do::

            # premium user has access to dashboard?
            >>> if settings.flag('dashboard', 'premiumuser'):
            ...     activate_dashboard()

        The value is ensured to be loaded fresh from redis server

        It also works with file settings but the recommended is redis
        as the data can be loaded once it is updated.

        :param key: The flag name
        :param env: The env to look for
        """
        ...

    def populate_obj(
        self, obj, keys=..., ignore=..., internal=..., convert_to_dict=...
    ):  # -> None:
        """Given the `obj` populate it using self.store items.

        :param obj: An object to be populated, a class instance.
        :param keys: A list of keys to be included.
        :param ignore: A list of keys to be excluded.
        :param internal: Include internal keys.
        :param convert_to_dict: Convert the settings to a pure dict (no Box)
         before populating.
        """
        ...

    def dynaconf_clone(self):  # -> Self:
        """Clone the current settings object."""
        ...

    @property
    def dynaconf(self):  # -> AttrProxy:
        """A proxy to access internal methods and attributes

        Starting in 3.0.0 Dynaconf now allows first level lower case
        keys that are not reserved keyword, so this is a proxy to
        internal methods and attrs.
        """
        class AttrProxy: ...

    @property
    def logger(self):  # -> Logger:
        """backwards compatibility with pre 3.0 loaders
        In dynaconf 3.0.0 logger and debug messages has been removed.
        """
        ...

    def is_overridden(self, setting):  # -> Literal[False]:
        """This is to provide Django DJDT support: issue 382"""
        ...

UPPER_DEFAULT_SETTINGS = ...
RESERVED_ATTRS = ...
