"""
This type stub file was generated by pyright.
"""

import os
from dynaconf.utils.functional import empty
from dynaconf.vendor import click

CWD = ...
EXTS = ...
WRITERS = ...
ENC = ...

def set_settings(ctx, instance=...):  # -> None:
    """Pick correct settings instance and set it to a global variable."""
    ...

def import__django_settings(django_settings_module):  # -> ModuleType | None:
    """Import the Django settings module from the string importable path."""
    ...

def import_settings(dotted_path):  # -> Any | None:
    """Import settings instance from python dotted path.

    Last item in dotted path must be settings instance.

    Example: import_settings('path.to.settings')
    """
    ...

def split_vars(
    _vars,
):  # -> dict[str, Any | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None]:
    """Splits values like foo=bar=zaz in {'foo': 'bar=zaz'}"""
    ...

def read_file_in_root_directory(*names, **kwargs):
    """Read a file on root dir."""
    ...

def print_version(ctx, param, value):  # -> None:
    ...
def open_docs(ctx, param, value):  # -> None:
    ...
def show_banner(ctx, param, value):  # -> None:
    """Shows dynaconf awesome banner"""
    ...

@click.group()
@click.option(
    "--version",
    is_flag=True,
    callback=print_version,
    expose_value=False,
    is_eager=True,
    help="Show dynaconf version",
)
@click.option(
    "--docs",
    is_flag=True,
    callback=open_docs,
    expose_value=False,
    is_eager=True,
    help="Open documentation in browser",
)
@click.option(
    "--banner",
    is_flag=True,
    callback=show_banner,
    expose_value=False,
    is_eager=True,
    help="Show awesome banner",
)
@click.option(
    "--instance",
    "-i",
    default=None,
    envvar="INSTANCE_FOR_DYNACONF",
    help="Custom instance of LazySettings",
)
@click.pass_context
def main(ctx, instance):  # -> None:
    """Dynaconf - Command Line Interface\n
    Documentation: https://dynaconf.com/
    """
    ...

@main.command()
@click.option("--format", "fileformat", "-f", default="toml", type=click.Choice(EXTS))
@click.option("--path", "-p", default=CWD, help="defaults to current directory")
@click.option(
    "--env",
    "-e",
    default=None,
    help="deprecated command (kept for compatibility but unused)",
)
@click.option(
    "--vars",
    "_vars",
    "-v",
    multiple=True,
    default=None,
    help="extra values to write to settings file "
    "e.g: `dynaconf init -v NAME=foo -v X=2`",
)
@click.option(
    "--secrets",
    "_secrets",
    "-s",
    multiple=True,
    default=None,
    help="secret key values to be written in .secrets "
    "e.g: `dynaconf init -s TOKEN=kdslmflds",
)
@click.option("--wg/--no-wg", default=True)
@click.option("-y", default=False, is_flag=True)
@click.option("--django", default=os.environ.get("DJANGO_SETTINGS_MODULE"))
@click.pass_context
def init(ctx, fileformat, path, env, _vars, _secrets, wg, y, django):  # -> None:
    """
    Inits a dynaconf project.

    By default it creates a settings.toml and a .secrets.toml
    for [default|development|staging|testing|production|global] envs.

    The format of the files can be changed passing
    --format=yaml|json|ini|py.

    This command must run on the project's root folder or you must pass
    --path=/myproject/root/folder.

    The --env/-e is deprecated (kept for compatibility but unused)
    """
    ...

@main.command(name="get")
@click.argument("key", required=True)
@click.option(
    "--default", "-d", default=empty, help="Default value if settings doesn't exist"
)
@click.option("--env", "-e", default=None, help="Filters the env to get the values")
@click.option(
    "--unparse",
    "-u",
    default=False,
    help="Unparse data by adding markers such as @none, @int etc..",
    is_flag=True,
)
def get(key, default, env, unparse):  # -> None:
    """Returns the raw value for a settings key.

    If result is a dict, list or tuple it is printed as a valid json string.
    """
    ...

@main.command()
@click.argument("to", required=True, type=click.Choice(WRITERS))
@click.option(
    "--vars",
    "_vars",
    "-v",
    multiple=True,
    default=None,
    help="key values to be written e.g: `dynaconf write toml -e NAME=foo -e X=2`",
)
@click.option(
    "--secrets",
    "_secrets",
    "-s",
    multiple=True,
    default=None,
    help="secret key values to be written in .secrets "
    "e.g: `dynaconf write toml -s TOKEN=kdslmflds -s X=2`",
)
@click.option(
    "--path", "-p", default=CWD, help="defaults to current directory/settings.{ext}"
)
@click.option(
    "--env",
    "-e",
    default="default",
    help="env to write to defaults to DEVELOPMENT for files "
    "for external sources like Redis and Vault "
    "it will be DYNACONF or the value set in "
    "$ENVVAR_PREFIX_FOR_DYNACONF",
)
@click.option("-y", default=False, is_flag=True)
def write(to, _vars, _secrets, path, env, y):  # -> None:
    """Writes data to specific source."""
    ...

@main.command()
@click.option("--path", "-p", default=CWD, help="defaults to current directory")
def validate(path):  # -> None:
    """
    Validates Dynaconf settings based on provided rules.

    Rules should be defined in dynaconf_validators.toml
    """
    ...

INSPECT_FORMATS = ...

@main.command()
@click.option("--key", "-k", help="Filters result by key.")
@click.option(
    "--env",
    "-e",
    help="Filters result by environment on --report-mode=inspect.",
    default=None,
)
@click.option(
    "--format",
    "-f",
    help="The output format.",
    default="json",
    type=click.Choice(INSPECT_FORMATS),
)
@click.option(
    "--old-first",
    "new_first",
    "-s",
    help="Invert history sorting to 'old-first' on --report-mode=inspect.",
    default=True,
    is_flag=True,
)
@click.option(
    "--limit",
    "history_limit",
    "-n",
    default=None,
    type=int,
    help="Limits how many history entries are shown on --report-mode=inspect.",
)
@click.option(
    "--all",
    "_all",
    "-a",
    default=False,
    is_flag=True,
    help="Show dynaconf internal settings?",
)
@click.option(
    "--report-mode",
    "report_mode",
    "-m",
    default="inspect",
    type=click.Choice(["inspect", "debug"]),
)
@click.option(
    "-v",
    "--verbose",
    count=True,
    help="Increase verbosity of the output on --report-mode=debug.",
)
def inspect(
    key, env, format, new_first, history_limit, _all, report_mode, verbose
):  # -> None:
    """
    Inspect the loading history of the given settings instance.

    Filters by key and environment, otherwise shows all.
    """
    ...

if __name__ == "__main__": ...
