"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any, Callable
from dynaconf.base import Settings

__all__ = [
    "hookable",
    "EMPTY_VALUE",
    "Hook",
    "EagerValue",
    "HookValue",
    "MethodValue",
    "Action",
    "HookableSettings",
    "post_hook",
]

class Empty: ...

EMPTY_VALUE = ...

def hookable(
    function=..., name=...
):  # -> _Wrapped[..., object, ..., Any] | Callable[..., _Wrapped[..., Any, ..., Any]]:
    """Adds before and after hooks to any method.

    :param function: function to be decorated
    :param name: name of the method to be decorated (default to method name)
    :return: decorated function

    Usage:

        class MyHookableClass(Settings):
            @hookable
            def execute_loaders(....):
                # do whatever you want here
                return super().execute_loaders(....)

        settings = Dynaconf(_wrapper_class=MyHookableClass)

        def hook_function(temp_settings, value, ...):
            # do whatever you want here
            return value

        settings.add_hook("after_execute_loaders", Hook(function))

        settings.FOO
        # will trigger execute_loaders
        # -> will trigger the hookable method
        # -> will execute registered hooks

    see tests/test_hooking.py for more examples.
    """
    ...

def get_hooks(obj):  # -> Any | dict[Any, Any]:
    """get registered hooks from object
    must try different casing and accessors because of
    tests and casing mode set on dynaconf.
    """
    ...
@dataclass
class Hook:
    """Hook to wrap a callable on _registered_hooks list.

    :param callable: The callable to be wrapped

    The callable must accept the following arguments:

    - temp_settings: Settings or a Dict
    - value: The value to be processed wrapper in a HookValue
      (accumulated from previous hooks, last hook will receive the final value)
    - *args: The args passed to the original method
    - **kwargs: The kwargs passed to the original method

    The callable must return the value:

    - value: The processed value to be passed to the next hook
    """

    function: Callable
    ...

@dataclass
class HookValue:
    """Base class for hook values.
    Hooks must return a HookValue instance.
    """

    value: Any
    @classmethod
    def new(cls, value: Any) -> HookValue:
        """Return a new HookValue instance with the given value."""
        ...

    def __str__(self) -> str: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self):  # -> Any:
        ...
    def __getitem__(self, item):  # -> Any:
        ...
    def __setitem__(self, key, value):  # -> None:
        ...
    def __delitem__(self, key):  # -> None:
        ...
    def __contains__(self, item):  # -> bool:
        ...
    def __getattr__(self, item):  # -> Any:
        ...
    def __setattr__(self, key, value):  # -> None:
        ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __mul__(self, other): ...
    def __truediv__(self, other): ...
    def __floordiv__(self, other): ...
    def __mod__(self, other): ...
    def __divmod__(self, other):  # -> Any:
        ...
    def __pow__(self, power, modulo=...): ...
    def __delattr__(self, item):  # -> None:
        ...
    def __repr__(self) -> str: ...

class MethodValue(HookValue):
    """A value returned by a method
    The main decorated method have its value wrapped in this class
    """

    ...

class EagerValue(HookValue):
    """Use this wrapper to return earlier from a hook.
    Main function is bypassed and value is passed to after hooks."""

    ...

class Action(str, Enum):
    """All the hookable functions"""

    AFTER_GET = ...
    BEFORE_GET = ...

class HookableSettings(Settings):
    """Wrapper for dynaconf.base.Settings that adds hooks to get method."""

    _REGISTERED_HOOKS: dict[Action, list[Hook]] = ...
    @hookable
    def get(
        self, *args, **kwargs
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        ...

class TempSettingsHolder:
    """Holds settings to be passed down to hooks.
    To save runtime resources initialize a copy of it only if accessed.
    """

    _settings = ...
    def __init__(self, settings) -> None: ...
    def __getattr__(self, attr):  # -> Any:
        ...
    def __getitem__(
        self, item
    ):  # -> Del | Insert | Merge | Reset | Lazy | str | int | float | bool | Any | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Del | Insert | Merge | Reset | Any | Lazy | str | int | float | bool | Empty | list[Any | list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Lazy | int | float | bool | Empty | None] | DynaBox | dict[Any, Any] | BoxList | Box | object | list[list[Any] | DynaBox | dict[Any, Any] | str | Del | Insert | Merge | Reset | Any | Lazy | int | float | bool | Empty | None] | list[Any] | None] | None:
        ...
    def __setitem__(self, item, value):  # -> None:
        ...
    def __iter__(self): ...
    def __contains__(self, item):  # -> bool:
        ...
    def __setattr__(self, attr, value):  # -> None:
        ...

def post_hook(function: Callable) -> Callable:
    """This decorator marks a function as a post hook.
    This works by adding the _dynaconf_hook attribute to the function,
    then the python loader, when reading the module, will look for
    this attribute and register the function as a post_hook for the settings.

    e.g: On a settings file with .py extension:

    from dynaconf import post_hook
    @post_hook
    def set_log_handlers(settings) -> dict:
        data = {}  # data to be merged into settings

        # conditionals
        if (logging := settings.get('LOGGING')) is not None:
            # do something with logging
            # add it back to data
            data['LOGGING'] = logging
        return data
    """
    ...
