"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable, Sequence, TYPE_CHECKING
from dynaconf.base import Settings

if TYPE_CHECKING: ...
EQUALITY_ATTRS = ...

class ValidationError(Exception):
    """Raised when a validation fails"""
    def __init__(self, message: str, *args, **kwargs) -> None: ...

class Validator:
    """Validators are conditions attached to settings variables names
    or patterns::

        Validator('MESSAGE', must_exist=True, eq='Hello World')

    The above ensure MESSAGE is available in default env and
    is equal to 'Hello World'

    `names` are a one (or more) names or patterns::

        Validator('NAME')
        Validator('NAME', 'OTHER_NAME', 'EVEN_OTHER')
        Validator(r'^NAME', r'OTHER./*')

    The `operations` are::

        eq: value == other
        ne: value != other
        gt: value > other
        lt: value < other
        gte: value >= other
        lte: value <= other
        is_type_of: isinstance(value, type)
        is_in:  value in sequence
        is_not_in: value not in sequence
        identity: value is other
        cont: contain value in
        len_eq: len(value) == other
        len_ne: len(value) != other
        len_min: len(value) > other
        len_max: len(value) < other

    `env` is which env to be checked, can be a list or
    default is used.

    `when` holds a validator and its return decides if validator runs or not::

        Validator('NAME', must_exist=True, when=Validator('OTHER', eq=2))
        # NAME is required only if OTHER eq to 2
        # When the very first thing to be performed when passed.
        # if no env is passed to `when` it is inherited

    `must_exist` is alias to `required` requirement. (executed after when)::

       settings.get(value, empty) returns non empty

    condition is a callable to be executed and return boolean::

       Validator('NAME', condition=lambda x: x == 1)
       # it is executed before operations.

    """

    default_messages = ...
    def __init__(
        self,
        *names: str,
        must_exist: bool | None = ...,
        required: bool | None = ...,
        condition: Callable[[Any], bool] | None = ...,
        when: Validator | None = ...,
        env: str | Sequence[str] | None = ...,
        messages: dict[str, str] | None = ...,
        cast: Callable[[Any], Any] | None = ...,
        default: Any | Callable[[Any, Validator], Any] | None = ...,
        description: str | None = ...,
        apply_default_on_none: bool | None = ...,
        **operations: Any,
    ) -> None: ...
    def __or__(self, other: Validator) -> CombinedValidator: ...
    def __and__(self, other: Validator) -> CombinedValidator: ...
    def __eq__(self, other: object) -> bool: ...
    def validate(
        self,
        settings: Settings,
        only: str | Sequence | None = ...,
        exclude: str | Sequence | None = ...,
        only_current_env: bool = ...,
    ) -> None:
        """Raise ValidationError if invalid"""
        ...

class CombinedValidator(Validator):
    def __init__(
        self, validator_a: Validator, validator_b: Validator, *args: Any, **kwargs: Any
    ) -> None:
        """Takes 2 validators and combines the validation"""
        ...

    def validate(
        self,
        settings: Any,
        only: str | Sequence | None = ...,
        exclude: str | Sequence | None = ...,
        only_current_env: bool = ...,
    ) -> None: ...

class OrValidator(CombinedValidator):
    """Evaluates on Validator() | Validator()"""
    def validate(
        self,
        settings: Any,
        only: str | Sequence | None = ...,
        exclude: str | Sequence | None = ...,
        only_current_env: bool = ...,
    ) -> None:
        """Ensure at least one of the validators are valid"""
        ...

class AndValidator(CombinedValidator):
    """Evaluates on Validator() & Validator()"""
    def validate(
        self,
        settings: Any,
        only: str | Sequence | None = ...,
        exclude: str | Sequence | None = ...,
        only_current_env: bool = ...,
    ) -> None:
        """Ensure both the validators are valid"""
        ...

class ValidatorList(list):
    def __init__(
        self,
        settings: Settings,
        validators: Sequence[Validator] | None = ...,
        *args: Validator,
        **kwargs: Any,
    ) -> None: ...
    def register(self, *args: Validator, **kwargs: Validator):  # -> None:
        ...
    def descriptions(self, flat: bool = ...) -> dict[str, str | list[str]]: ...
    def validate(
        self,
        only: str | Sequence | None = ...,
        exclude: str | Sequence | None = ...,
        only_current_env: bool = ...,
    ) -> None: ...
    def validate_all(
        self,
        only: str | Sequence | None = ...,
        exclude: str | Sequence | None = ...,
        only_current_env: bool = ...,
    ) -> None: ...
