"""
This type stub file was generated by pyright.
"""

"""
Implement basic assertions to be used in assertion action
"""

def eq(value, other):
    """Equal"""
    ...

def ne(value, other):
    """Not equal"""
    ...

def gt(value, other):
    """Greater than"""
    ...

def lt(value, other):
    """Lower than"""
    ...

def gte(value, other):
    """Greater than or equal"""
    ...

def lte(value, other):
    """Lower than or equal"""
    ...

def identity(value, other):  # -> bool:
    """Identity check using ID"""
    ...

def is_type_of(value, other):  # -> bool:
    """Type check"""
    ...

def is_in(value, other):  # -> bool:
    """Existence"""
    ...

def is_not_in(value, other):  # -> bool:
    """Inexistence"""
    ...

def cont(value, other):  # -> bool:
    """Contains"""
    ...

def len_eq(value, other):
    """Length Equal"""
    ...

def len_ne(value, other):
    """Length Not equal"""
    ...

def len_min(value, other):
    """Minimum length"""
    ...

def len_max(value, other):
    """Maximum length"""
    ...

def startswith(value, term):
    """returns value.startswith(term) result"""
    ...

def endswith(value, term):
    """returns value.endswith(term) result"""
    ...
